openapi: "3.0.3"
info:
  title: Hoist Auth API
  version: "1.0.0"
  description: Authentication, registration, and account management endpoints

paths:
  /api/users/register:
    post:
      operationId: registerUser
      summary: Register a new user with email/password
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: Registration successful, verification email sent
        "400":
          description: Validation errors (missing fields, weak password, duplicate email, underage)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationProblem"

  /api/users/login:
    post:
      operationId: loginUser
      summary: Login with email and password
      description: Returns bearer token. Rejects unverified accounts with a specific error code.
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Invalid credentials or email not verified

  /api/users/google-login:
    post:
      operationId: googleLogin
      summary: Login or register via Google OAuth token exchange
      description: >
        Accepts a Google OAuth ID token obtained from the mobile client.
        If a user with the matching email exists, links Google identity
        and returns bearer token. If no user exists, creates a new account
        with Google profile data (email pre-verified) and returns bearer token.
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleLoginRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Invalid or expired Google token

  /api/users/verify-email:
    post:
      operationId: verifyEmail
      summary: Verify email address using token from verification email
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyEmailRequest"
      responses:
        "200":
          description: Email verified successfully
        "400":
          description: Invalid or expired token

  /api/users/resend-verification:
    post:
      operationId: resendVerification
      summary: Resend email verification for an unverified account
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResendVerificationRequest"
      responses:
        "200":
          description: Verification email sent (always returns 200 to prevent enumeration)

  /api/users/forgot-password:
    post:
      operationId: forgotPassword
      summary: Request a password reset email
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordRequest"
      responses:
        "200":
          description: >
            Password reset email sent if account exists
            (always returns 200 to prevent email enumeration)

  /api/users/reset-password:
    post:
      operationId: resetPassword
      summary: Reset password using token from reset email
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordRequest"
      responses:
        "200":
          description: Password reset successfully
        "400":
          description: Invalid or expired token, or password does not meet requirements

  /api/users/refresh:
    post:
      operationId: refreshToken
      summary: Refresh an expired bearer token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        "200":
          description: New token pair
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Invalid refresh token

components:
  schemas:
    RegisterRequest:
      type: object
      required: [email, password, firstName, lastName]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
        firstName:
          type: string
          maxLength: 100
        lastName:
          type: string
          maxLength: 100
        age:
          type: integer
          minimum: 13
          nullable: true

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    GoogleLoginRequest:
      type: object
      required: [idToken]
      properties:
        idToken:
          type: string
          description: Google OAuth ID token from client-side auth

    VerifyEmailRequest:
      type: object
      required: [userId, token]
      properties:
        userId:
          type: string
        token:
          type: string

    ResendVerificationRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email

    ForgotPasswordRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email

    ResetPasswordRequest:
      type: object
      required: [email, token, newPassword]
      properties:
        email:
          type: string
          format: email
        token:
          type: string
        newPassword:
          type: string
          minLength: 8

    RefreshRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string

    TokenResponse:
      type: object
      properties:
        tokenType:
          type: string
          example: Bearer
        accessToken:
          type: string
        expiresIn:
          type: integer
        refreshToken:
          type: string

    ValidationProblem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
